### ISSUE TITLE
Lab: Getting Started Revisions

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#14]
# Overview

Fall 2022: There were a lot of small issues with this lab. 

First of all, I think it’s fine for them to continue working in groups, but I think each person should turn in their own lab. The fact that some groups turned in one lab for the whole group and other groups turned in one lab per person made grading really difficult. If you do this, make sure to remove the current question 1 about group members. 

Also, make sure to cover how to create data frames and HTML markdown documents in the lab warm-up. Students were really bad at both. You may want to consider just having them turn in their HTML file and using a grading rubric. I think it was a little confusing/redundant having them copy and paste their code into the text boxes on the quiz.

Make sure they can see the correct answer _before_ submitting the lab.

**2023-08-18**: I think I should change the entire lab to be self-grading.

**2023-08-22**: Ideas for lab tasks/questons

- [x] Open R/RStudio/Posit Cloud
- [x] Open a qmd document
- [x] Create HTML output - embed resources
- [x] Add headers to qmd document
- [x] Add markdown text to qmd document
- [x] Download study forms
- [x] Add code blocks
- [x] Load packages
- [x] Create data frame
  - [x] I will choose the variables - all 4 
  - [x] Naming objects
  - [x] data frames vs tibbles
  - [x] Various methods for creating a data frame
  - [x] Simulating data - point this out
  - [x] Keyboard shortcut for running code chunk
  - [x] rep() function
  - [x] c() function
  - [x] Good variable names
  - [x] Factors
- [x] Print to screen
- [x] Optional feedback

# Tasks

- [x] Create lab in RStudio/Word.
- [ ] Upload to Posit Cloud.
- [ ] Create a Word document version.
- [ ] Create the lab on Canvas.
