### ISSUE TITLE
Measures of Occurrence Module Revisions - Fall 2023

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#17]
# Overview

In **Fall 2022**, I was in Miami during the week this module was being prepped and I didn’t get nearly as much work done as I intended. Here is a [link to the task](https://tasks.office.com/uthtmc.onmicrosoft.com/en-US/Home/Planner/#/plantaskboard?groupId=18d472e3-5bc6-4aa2-83f9-21b6bde19cc8&planId=vJvqI4O250S7s4yQqcEfnGQABuev) in Teams. As a quick summary:

- I moved over the lab and module quiz from intro to R – descriptive analysis I. This is an ok start, but I need to add questions about prevalence, incidence, etc. It’s fine to use examples from the Szklo book as a start.
  - Actually, Libby didn’t move this over in time. So, the wrong lab was posted initially. Because students had already started the lab, we couldn’t unpublish it. Instead, we had to add a new lab called measures of occurrence 2022. Next semester, possibly combine questions from both and just have one lab. 
  - Make sure they can see the correct answer _before_ submitting the lab. 
- I created lab warm-up slides. This is what we spent the majority of our in-class time going over. I basically just gave a lecture. By next semester, I’d like to turn this material into a chapter of R4Epi and assign it as reading. Then, spend class time on a short lab warm-up (Socrative) and working on the lab.
- Because I basically just lectured the entire class time, and because we never got around to create a module quiz, I let them have until Sunday at midnight to complete the lab. Next semester, make sure the change the due date back to the end of the lab session. 

## Notes

For tomorrow, I need the following:

- Lab warm-up
- Lab
- Module quz
- Realistically, I’m not going to be able to create all three. So, where should I concentrate my time?
  - Improve the lab. Don’t worry about the word document right now. Just build it in Canvs/RStudio.
  - We can do the class without a lab warm-up or with a really hastily made lab warm-up if we need to.
  - We can also do without a module quiz.

# Tasks 

- [x] Make lab. 
  - [x] Add code link to lab instructions 
- [x] Add module quiz to Canvas
- [x] Make lab warm-up
- [x] Add more measures of occurrence-type questions to the lab
- [x] Update the overview if you add more measures of occurrence stuff
- [x] Add lab code to Posit Cloud
- [x] Update the lab agenda
