### ISSUE TITLE
Systematic Error - Bias Module Revisions - Fall 2023

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#19]
# Overview

This semester, I finally formally added random (sampling error) to the course. I added it into the bias section, which sort of makes sense. In the beginning of the section, we talk about random error and systematic error. **Next semester, I think I should make these into two separate modules: Random Error – Sampling Variability and Systematic Error – Bias**. And because these concepts apply to all analysis goals – not just causal inference – I may want to put them before the causal inference module. At least the random error module. Maybe right after measures of occurrence. Or maybe right after intro to regression. 

# Tasks

- [x] Review bias exercises in Szklo and Nieto (pg. 171)
- [x] Review bias exercises from Hernan's course on EDX (Epi III > Resources > hernan > edX course)
- [x] Update links in the lab instructions
- [ ] Update lab in RStudio and Canvas (Remember, it doesn't have to be perfect right away)
  - [x] Add multiple choice questions to the lab
  - [x] Convert Libby's lab into the module quiz
  - [ ] If time, Add structural definitions to lab warm-up PP (and make a note of it in [GitHub](https://github.com/orgs/brad-cannell/projects/3/views/6?pane=issue&itemId=40756218)). If not, make a note to do this in [2024](https://github.com/orgs/brad-cannell/projects/11/views/3?pane=issue&itemId=41725374).
  - [ ] If you add structural definitions to lab warm-up slides, and if there's time, then add questions to lab and quiz. If not, make a note to do this in [2024](https://github.com/orgs/brad-cannell/projects/11/views/3?pane=issue&itemId=41725374).
- [x] Add lab warm-up and slides to Canvas
- [x] Add lab code to Posit
