### ISSUE TITLE
Cohort Studies Module Revisions - Fall 2023

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#20]
# Overview

## Fall 2022

I left all of survival analysis until this module this semester. I think this was a bad idea. **Next semester, I think I should add non-regression survival analysis to the measures of occurrence and association modules, and I should add Cox regression to the regression module**. This module should basically just be a chance to practice those concepts again.

I removed slides on the manual calculation of confidence intervals from the cohort analysis module in the Fall of 2022. **We may want to move teaching these calculations over to the random error module**. Or, we may just want to leave teaching the manual calculation of confidence intervals to biostatistics courses. Or, we may just want to teach the manual calculation of one confidence interval (e.g., a mean) -- not because they need to know how to do manual calculations in the real world -- but to help us understand how to correctly interpret confidence intervals by helping us understand what is really going on under the hood. 

## Fall 2023

I'm not actually sure that it's so bad to wait until this module to introduce survival analysis.
1. The measures of association chapter is already pretty busy.
2. Survival analysis is really only used with cohort studies. 
So, maybe we don't need to move that material after all. Just improve, and more tightly integrate, it.

Keep the survival analysis slides separate because they will be in a separate chapter of R4Epi. You can still discuss them this week. They just need to be in a separate slide deck.

Update: After teaching this module again, I think we should: 
- Introduce the life table and Kaplan-Meier methods in the measures of association module.
- Review the life table and Kaplan-Meier methods in the cohort studies module.
- Introduce Cox PH regression in the cohort studies module.

### Random error

- I thought about adding material on calculating p-values, confidence intervals, and p-value curves to this module. However:
- I was short on time.
- I think I want to introduce these calculations in the measures of association module. That doesn't mean we can't also do them here. In fact, we should. But, I want to introduce them there.
- There are formulas in the cohort_studies_analysis slides.

### Lab warm-up

- Perhaps turn this into a separate task.
- There are outputs and plots in the code that are clearly from R for a couple of the examples (kidney transplant and DPCA), but I can't find the code that was used to make them anywhere. I searched GH, SharePoint, and Dropbox extensively. I think I will just need to recreate them.

### Lab

- I combined the questions from the old cohort design and cohort analysis modules, but I didn't have time to do much else.

### Module quiz

- I combined the questions from the old cohort design and cohort analysis modules, but I didn't have time to do much else.

# Tasks

- [x] Combine module content on SharePoint
- [x] Delete Check on Learning: Cohort Study Analysis (it is an empty shell)
- [x] Add questions from Check on Learning: Cohort Studies II to Check on Learning: Cohort Studies
- [x] Delete Check on Learning: Cohort Studies II
- [x] Add one question from BOW chapter 7 to Check on Learning: Cohort Studies
- [x] Create COL shell for experimental studies and move the BOW chapter 6 question from Check on Learning: Cohort Studies to the new shell. Make a note in the experimental studies GH task.
- [x] Add combined (design and analysis) COL to Canvas
- [x] Post an announcement on Canvas about readings and COL
- [x] Add combined (design and analysis) lab to Canvas
- [x] Add combined (design and analysis) module quiz to Canvas
- [x] Create a combined (design and analysis) lab warm-up
  - [x] Move over analysis slides
  - [ ] Figure out inverse time and the relationship between IPR and IRR. Add notes to measures of association as well.
  - [x] Create a QMD file to accompany the cohort studies slides
  - [ ] Create a QMD file to accompany the survival analysis slides. Started this, but didn't finish.
- [x] Add lab warm-up slides to Canvas
- [ ] Test out deleting quiz questions from a quiz vs deleting completely from Canvas
- [ ] Create Socrative/Poll everywhere to accompany the lab warm-up
- [ ] Review the combined lab for[ errors and opportunities for improvement](https://github.com/brad-cannell/epi_3_public/issues/61)
- [ ] Review the combined module quiz for[ errors and opportunities for improvement](https://github.com/brad-cannell/epi_3_public/issues/62)
- [ ] Make Figure 2-1 from Szklo and Nieto in the lab warm-up. I think I can recreate this with geom_segment, but I don't have time to try at the moment.
- [ ] Add better comments to the code in the lab warm-up. What is each line (or so) doing?
- [ ] Clean up (or paraphrase) the quotes from S&N in the lab warm-up. For example, there are some subscripts (equations) and citation numbers.
- [ ] Add combined (design and analysis) slides to R4Epi
- [ ] Add R4Epi reading to module overview page
- [ ] Introduce competing risks (see Modern Epidemiology, chapter 4)
- [ ] Introduce time-varying exposures (see "Categorizing Cases, Persons, and Person-Time" in Modern Epidemiology, p. 147)
- [ ] Incorporate information from [the hazards of hazard ratios](https://paperpile.com/app/p/77c7da6b-d453-0b59-b320-5c911ea90927)
- [ ] Add any remaining stuff to task(s) for 2024
