### ISSUE TITLE
Create Discussion Board

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#21]
# Overview

Create a discussion board for Epi III. Use it in the same way you use the [discussion board for Intro to R](https://github.com/brad-cannell/intro.r.public/discussions). 

At the end of each lab, create a text "question" titled `Optional Feedback` that says: "**Optional**: You can post questions about this lab on the [GitHub discussion board](https://github.com/brad-cannell/epi_3_public/discussions). You are also welcome to leave comments about the usefulness of this lab. Which parts were helpful? What could I do to improve it? What is still unclear?" Make sure to update the GitHub link.

# Left off at

2023-08-02: Adding links to lab discussion boards to the labs. Need to update epi_3_public and epi_3_private first (#8).
- I just finished adjusting the repos and Uploading them to SharePoint. I need them to finish uploading so that I can add the links to Canvas.
- Then pick up with Measures of Occurrence.

# Tasks

- [x] Create all of the individual lab discussion boards
- [x] Add links to lab discussion boards to the labs. And while you are updating each lab:
  - #10
  - Update links to R Notebook files (need to update epi_3_public first). Remove the HTML versions of the files.
  - Update the due date (lab date 4:00 PM) and available from date (lab date 2:00 PM).
- [x] Make sure the style of all the lab links to Rmd files is uniform. (use the style from the confounding module).

**Comment by mbcann01** [comment]
2023-08-04: I did all the tasks above for _existing_ modules. Of course, there are modules that still need to be built out.
