### ISSUE TITLE
Use Posit Cloud

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#22]
# Overview

Decide if I should have the students do R stuff in [Posit Cloud](https://posit.cloud/) or not. 

If so, I think I will need to give them options.
- Download and use R/RStudio locally.
- Pay for their own Posit Cloud account.
- Get a free Posit Cloud account?

**Note**: The project has a download button in Posit cloud. Students who don't want to pay for Posit Cloud, or prefer to work in RStudio locally, can just create a free account, download the files locally, and do their work there.

## Useful sites

- [Posit Cloud pricing](https://posit.cloud/plans)
- [Guide for teaching with Posit Cloud](https://posit.cloud/learn/guide#teach)
- [Working with GitHub](https://posit.cloud/learn/guide?_gl=1*tsk778*_ga*MTM3NDY5NTU5LjE2ODkxNzAyMDA.*_ga_8PLL5FXR9M*MTY5MTE4MDU2Ny43LjAuMTY5MTE4MDU2Ny4wLjAuMA..*_ga_2C0WZ1JHG0*MTY5MTE4MDU2Ny44LjAuMTY5MTE4MDU2Ny4wLjAuMA..#github-details)

## Pushing to GitHub from Posit Cloud

We can push edits back up to GitHub. See the [working with GitHub](https://posit.cloud/learn/guide?_gl=1*pcavhk*_ga*MTM3NDY5NTU5LjE2ODkxNzAyMDA.*_ga_8PLL5FXR9M*MTY5MTE4MDU2Ny43LjAuMTY5MTE4MDU2Ny4wLjAuMA..*_ga_2C0WZ1JHG0*MTY5MTE4MDU2Ny44LjAuMTY5MTE4MDU2Ny4wLjAuMA..#github-details) article.

1. Press `New Project` > `New Project from GitHub Repository`.
2. Enter the HTTPS URL for the repo.
3. When you are ready to push something to GitHub
    1. Create a personal access token on GitHub in [Developer Settings](https://github.com/settings/apps). Give it access to everything. 
    2. Click push or type `git push` in the terminal. 
    3. Enter your user name.
    4. Copy and paste the token from step 1 into password. If you do this in the terminal, it won't look like anything was pasted in. Just paste one time.
    5. It should push.

## Creating one big project for the course vs one project for each assignment

It seems like there could be a conflict between using a single GitHub repo for the entire course and creating a separate GitHub repo for each assignment. 

- Is there a way to have the best of both worlds? Keep all Rmd documents in a single GitHub repo, but turn only individual rmd documents into assignments in Posit Cloud? 
  - It doesn't seem like this is possible.
- What is even the advantage of making it an [assignment](https://posit.cloud/learn/guide#teach-create-assignments)? Go back and read about that.
  - The advantages are: Posit Cloud will automatically make a copy for them.
- One of the downsides to using one repo for all the assignments is that the Files pane is really busy. Especially since I set up the `epi_III_public` repo as an R package. 

### Here's what I think I want to do:

- Keep the `epi_III_public` repo as it is for now. Even the R package files. 
- However, don't upload it as a project in Posit Cloud.
- Still use the `epi_III_public` repo for tracking issues, wiki, and discussions.
- You can also keep files for creating Rds files (e.g., study.R) in this repo.
- Create a separate Posit Cloud project for each lab assignment (but not a repo). 
- Manually upload .qmd documents to Posit Cloud.

Or... Maybe I just want to delete all of the R project files from the `epi_III_public` repo and just have one repo for all labs. Test out one first and see how it goes? As long as you don't delete the `epi_III_public` repo, you can always go back to using it as you were before.

# Left off at

2023-08-18
- I think I'm going to create separate assignments directly in Posti Cloud for now, but not separate repos in GitHub. That seems like too much to track. I will upload and download the qmd files to/from Posit Cloud as needed. Once the files are in good shape, this shouldn't happen very often. 
- I'm going to step away from this for the moment and make sure more critical aspects of week 1 and 2 are ready to go. I can come back to this later.

# Tasks

- [x] Try creating a new project from the epi_3_public repo.
- [x] Can/should we push changes back to GitHub?
- [x] Create a single assignment and see what it looks like from the student perspective.
- [x] Create an example repo and Posit cloud project for the measures of occurrence module. 
- [x] Create instructions for students for using Posit Cloud. Sign up for an account. Downloading files if you don't want to pay. Use as much of Posit's existing documentation as possible.
- [ ] Work on Measures of Occurrence module. Convert to .qmd.
- [ ] Upload the labs for the other modules that are already ready to go.
