### ISSUE TITLE
Create the Random Error Module

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#26]
# Overview

**Fall 2023**

- This will be a new module in Fall 2023. Need to create it.
- I didn't have time to write a chapter on random error in R4Epi (brad-cannell/r4epi#106). I assigned Modern Epidemiology chapter 15 instead. 
- My intent is to create a lab warm-up in PowerPoint that can serve as a foundation for the random error chapter in R4Epi.
- If I get that PowerPoint made this week, then I can start the chapter by moving that content over.

For Tuesday (9/19), I need the following:

- Lab warm-up
- Lab
- Module quiz
- Realistically, I’m not going to be able to create all three. So, where should I concentrate my time?
  - This is brand new. Just do it as a lecture. The lecture can be turned into a chapter.
  - Alternatively, maybe I just create a lab based on the readings.
  - Use most of my time this week making sure that Measures of Association is good to go. 

# Tasks 

- [x] Add readings to [the reading list](https://uthtmc.sharepoint.com/:x:/r/sites/SPHCannellEpiIII/_layouts/15/Doc.aspx?sourcedoc=%7BE4ACCA9A-C366-4C25-A26E-F76766D82266%7D&file=Readings.xlsx&action=default&mobileredirect=true)
- [x] Create a module overview page
- [ ] Create a COL quiz
- [ ] Create a lab warm-up
- [ ] Create a lab
- [ ] Create a module quiz
- [ ] Simulate differential and non-differential misclassification using the methods in [Rudolph and Fox](https://paperpile.com/app/p/d038668a-e7f6-0461-be36-263ab32fdce0), example 2.
