### ISSUE TITLE
Getting Started Module Revisions - Fall 2023

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#28]
# Overview

A running list of little tasks to prep for Fall 2023.

## Changing module name

I want to change the name of the module from `Getting started with R and RStudio` to `Getting Started`. Why? for at least two reasons:
1. I want to start using Posit Cloud instead of downloading and using R and RStudio.
2. I want it to also be a review of Epi I.

## Lab warm-up

Fall 2022: Also, make sure to cover how to create data frames and HTML markdown documents in the lab warm-up. Students were really bad at both. You may want to consider just having them turn in their HTML file and using a grading rubric. I think it was a little confusing/redundant having them copy and paste their code into the text boxes on the quiz.

# Left off at

2023-08-22

- Working on the getting started lab (#14)

# Tasks

- [x] Change module name from `Getting started with R and RStudio` to `Getting Started`
- [x] COL: Getting Started Revisions #11.
- [x] Delete `Check on Learning: Introduction and Review` from Canvas to avoid confusion in the future.
- [x] Add Into to epidemiology to the reading list. 
- [x] Create instructions for setting up a Posit Cloud account.
- [x] Update the module overview to reflect the use of Posit Cloud.
- [x] Add a separate document showing how to use Posit Cloud. Rely on the Posti Cloud documentation as much as possible.
- [x] Update the chapter on Pipes in R4Epi (https://github.com/orgs/brad-cannell/projects/3/views/4?pane=issue&itemId=36256492)
- [x] Update the COL questions about pipes
- [x] Update the chapter on R markdown documents in R4Epi
  - [x] Fix the mislabeled img folder, `02_r_scripts` to `01_r_scripts`
  - [x] Fix the paths in `01_r_scripts.Rmd`
  - [x] Replace R markdown images with Quarto images
- [x] Update the COL questions about R markdown documents
- [x] Publish the Canvas course
- [x] Update the getting started lab (#14). Make it entirely self-grading.
- [x] Welcome slides
  - [x] Add TAs and Dr. Feofanova to the day one slides.
  - [x] Can/should I make the slides with RevealJS?
- [x] Lab warm-up
  - [x] Can/should I make the slides with RevealJS? Find out if you can add poll questions. [Using Poll Everywhere](https://support.polleverywhere.com/hc/en-us/articles/1260801821849-Embed-an-activity)?
  - [x] Add creating data frames and HTML output to the lab warm-up (see explanation in #14).
  - [x] Cover factors
