### ISSUE TITLE
Lab: Data Transfer Revisions

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#4]
# Overview 

**2023-07-20**: If we decide to drop the data transfer module and only use simulated data, then this issue becomes obsolete.

I orignially created this task in the Fall epi 3 course. Some parts of it apply to this course too. Some parts will not.

This was our first semester using this lab. We adapted it from the R course. As such, we had to remove a couple of tasks/questions related to data manipulation. In the process, we found some errors and some other issues to address before teaching this course again. 

Replace the fwf question with some other file type. This isn't an R coding class and that example is really complicated. I think it's great for the R class, but it's overkill for Epi III. I think they just need to know how to import csv, Excel, Stata, and SAS.

Update the web address for the NHANES data. Do this in the explanatory text (Code, Word, and Canvas) - Not the actual link you are passing to the read_xpt() function. Many students were confused about downloading the data vs passing the web address directly to the read_xpt() function. This is just a lab, so add a lot more explanation to help them. I think think this website should work: https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/default.aspx?BeginYear=2015. Also, you may want to update the date of the data to something newer than 2015-2016. It shouldn't be difficult. 

Q5: Change answer choice 3. Right now, it is identical to answer choice 4 (the correct answer). I intended to change the numbers being passed to the widths argument to be incorrect. I was going to make them column starting positions instead of widths. Of course, you can disregard this if you through out the fwf question altogether.

Q9: Update the number of columns to 10. After removing the data manipulation portions of the lab, the correct number of columns in the data frame is 10 rather than 15. Of course, if you change the year of the NHANES data set you are using, this answer may change too.

Q10: Use a variable other than alq101_f. After removing the data manipulation portions of the lab, this variable no longer exists in their data frame.

2023-05-30: I updated the [code](https://uthtmc-my.sharepoint.com/:f:/r/personal/michael_b_cannell_uth_tmc_edu/Documents/03%20Teaching/01%20Courses%20-%20Current/Intro%20to%20R/intro.r.public/modules/04%20Data%20Transfer?csf=1&web=1&e=PrJOQf), the [Google Doc](https://docs.google.com/document/d/1t4zHsZCf2UPN3hDbL0DSOuaF0jnvUkgwPw1U16daHdo/edit), and the [Canvas quiz](https://uth.instructure.com/courses/79593/quizzes/100238) for Intro to Epi.  Some of it should be useful for updates to the Epi III version as well. Here is a [link](https://github.com/orgs/brad-cannell/projects/14/views/3?pane=issue&itemId=28245436) to what I did. 

Those changes will affect Q9 and Q10 above by default. The new NHANES data affects the number of columns, but we will also still need to account for no longer doing data management (i.e., creating factors). The new NHANES data affects Q10 because there is no longer a variable named alq101_f. If we remove the data manipulation portions of the lab, none of the `_f` variables will exist in the data frame.

# Tasks

- [ ] Replace the fwf question with some other file type - Code, Word, Canvas
- [ ] Update the web address for the NHANES data - Code, Word, Canvas
- [ ] Q5: Change answer choice 3 - Code, Word, Canvas
- [ ] Q9: Update the number of columns to 10 - Code, Word, Canvas
- [ ] Q10: Use a variable other than alq101_f  - Code, Word, Canvas
