### ISSUE TITLE
Introduction to Regression Module Revisions - Fall 2023

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#41]
# Overview

A running list of little tasks to prep for Fall 2023.

# Left off

2023-09-29: Complete first draft of the intro to regression chapter and the individual glm chapters.

# Tasks

- [x] Create the intro to regression chapter in R4Epi brad-cannell/r4epi#108
- [x] Review lab code
- [x] Add lab to Posit Cloud
- [x] Update lab instructions
- [x] Update lab text on Canvas. Add question feedback.
- [x] Create a module quiz in RStudio
- [x] Update paths to download the NHANES data in in Task 1
- [x] Create a module quiz in Canvas
- [x] Create module quiz in Posit Cloud
- [x] Review lab warm-up
