### ISSUE TITLE
Introduction to Causal Inference Module Revisions - Fall 2023

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#42]
# Overview

A running list of little tasks to prep for Fall 2023.

In this module, we just want to briefly introduce DAGs and go over how to build them in R. Later, when we discuss confounding, bias, and mediation, we will work with more complicated DAGs. 

For the lab and quiz, just have them interpret some SCC models and work with some basic DAG structures.

## Potential lab and quiz questions

- Create DAGS
- Identify R code that makes a particular DAG
- D-Separated or not

# Tasks

- [x] Finish the DAGs chapter
- [x] Review lab warm-up and print pdf
- [ ] Update the lab
- [ ] Add lab code to Posit
- [ ] Create a module quiz
- [ ] Add module quiz code to posit
