### ISSUE TITLE
Confounding Module Revisions - Fall 2023

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#43]
# Overview

A running list of little tasks to prep for Fall 2023.

For tomorrow (2023-10-24)
- Give the lab warm-up slides. Check these to make sure they are good to go.
- There is a lab already created. It can probably be improved, but it looks like there is something there ready to go right now. Therefore, leave it alone for now.
- It doesn't look like there is currently any sort of module quiz. After checking the lab warm-up slides, this may be your next biggest priority. Start by making slight modifications to the lab.

# Left off at

2023-10-23: There is no module quiz for confounding. Create one that mimics the lab. Remember that you can also just ask multiple-choice questions. For example, questions about the change in estimate method, traditional criteria, and d-separation rules. 

2023-10-19: Moved lab warm-up slides and code to R4Epi. However, I didn't have time to clean up the chapter. It still needs a ton of editing. For Fall 2023, I'm still going to give the lab warm-up PowerPoint presentation at the beginning of class. 

# Tasks

- [x] Move confounding lab warm-up (slides and code) to R4Epi
- [x] Update the lab warm-up slides
- [x] Review the module quiz
- [x] Create module quiz. Create it directly in Canvas to begin with. Make DAGs in R.
  - [x] Create multiple-choice questions from the slides.
  - [x] Create multiple-choice questions that mimic the lab.
