### ISSUE TITLE
Effect Measure Modification Module Revisions - Fall 2023

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#44]
# Overview

A running list of little tasks to prep for Fall 2023.

## Lab warm-up

- I've reviewed it. I might want to simplify it, but it isn't a priority at the moment.
- Create some R code to go along with the data examples. 

## Lab

- Started with a lab that Libby created in Fall 2022. It's good enough for this semester.
  - The lab starts with question 1 instead of task 1. I think we could easily make it start with task 1 if I figure out how to turn the table of data into an R matrix and then walk the students through it.
  - I think the format is basically good. We have them do some calculations and then determine if EMM is present on the multiplicative scale and on the additive scale using two methods: Observed vs expected and homogeneity of effects.
- In the future, we should:
  - Add regression!
  - Make it longer. Strive to have at least one example of each possible combination of assessment method (observed vs expected, homogeneity of effects, regression), presence of EMM (Yes/No), type of EMM (additive/multiplicative), direction of EMM (positive, negative, qualitative, quantitative).
  - Add more R programming (e.g., to do the calculations. Possibly using matrices and arrays. Definitely using regression).
  - Add questions that ask them to interpret the effect measures (e.g., IRR and IRD), not just calculate them. 
  - Walk through a proof of there always being EMM on at least one scale.

## Module quiz

- In Fall 2023, I just used R like a calculator.
- Make the revisions above to the lab, then make the module quiz match.

# Left off at

- 2023-10-31
  - Complete EMM Quiz

# Tasks

- [x] Review and revise the lab that Libby created on Canvas. Don't worry about R code to begin with. Just make sure there is something useable there and the language is good (e.g., risk ratios to incidence rate ratios, etc.).
- [x] Review and revise the module quiz that Libby created on Canvas. Don't worry about R code to begin with. Just make sure there is something useable there and the language is good (e.g., risk ratios to incidence rate ratios, etc.).
- [x] In the lab, check to make sure the differences in between effect measures when using the homogeneity method constitute a "meaningful" difference. 
- [x] Create R code for the lab. Start with the calculator method.
- [x] Create R code for the module quiz.
- [x] Carry over any remaining notes to the [Fall 2024 task](https://github.com/brad-cannell/epi_3_public/issues/58)
