### ISSUE TITLE
Case-control Studies Module Revisions - Fall 2023

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#46]
# Overview

A running list of little tasks to prep for Fall 2023.

## Lab warm-up

- In Fall 2023, I combined the case-control study design and analysis labs into a single lab warm-up.
- The questions are too difficult. They need to be reading comprehension only.
- Possibly add more information about primary vs secondary study base (see comments below).
- Calculate the OR from a 2x2 table first, then from logistic regression.

## Lab

- In Fall 2023, I combined the case-control study design and analysis labs into a single lab.
- It feels like a grabbag of questions rather than the questions building on each other. I guess that isn't necessarily a problem for now, but I'd like to give it more of a flow in the future.
- I'm noticing that a lot of the questions about case-control study design are from the "Remember" section of Bloom's Taxonomy. Can you make them more applied?
- Add a lot more calculating and interpreting measures of random error (p-values, CI's, Chi-Square, etc.)
- There were several questions in `Lab: Case-control Study Analysis` that I didn't move over to the new `Lab: Case-control Studies`. They weren't necessarily "bad," they were just repetitive. They were all about matched ORs. I'm deleting `Lab: Case-control Studies` in Canvas, so you will have to go back to 2022 to look them up if you want them in the future.
- Make sure to cover the study base principle.

## Module quiz

- In Fall 2023, I combined the case-control study design and analysis module quizzes into a single module quiz.
- I made it very short and simple. It needs to be improved in the future, but not randomly. It should reflect that material in the lab.

# Tasks

- [x] Test deleting Canvas quiz questions. Add notes to Wiki.
- [x] Add "Unfied Questions" to item bank
- [x] Add COL questions to item bank
- [x] Create a combined (design and analysis) COL from item bank
- [x] Review the COL questions in the item bank
- [x] Add design and analysis labs to separate question banks
- [x] Create a combined (design and analysis) lab
  - [x] Add design questions
  - [x] Add feedback for design questions
  - [x] Add analysis questions
- [x] Add an optional feedback question to the lab
- [x] Create a combined (design and analysis) quiz
  - [x] Add design questions
  - [x] Add analysis questions
- [x] Read through the slides once
- [x] Rehearse slides
- [x] Add slides to Canvas
- [x] Decide what to do about next week

**Comment by mbcann01** [comment]
# Primary vs secondary base
Primary base defined by the population under study
- Population-based studies
- Difficult to get every case

Secondary base defined by case definition
- Study base are those who would have been selected as cases if they developed the disease
- Hospital-based studies
