### ISSUE TITLE
Introduction to Causal Inference Module Revisions - Fall 2024

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#54]
# Overview

A running list of little tasks to prep for Fall 2024. In Fall 2023, I spent a lot of time working on the causal inference chapters, but I didn't have much time at all to work on the COL quiz, lab, or module quiz. **The lab and module quiz especially need some attention**. They do not fit the style of previous module quizzes. Meaning, there really is no R code. It's just multiple-choice questions. Also, I removed the link to the R code in the lab instructions. Make sure to add it back in if you feature R code more prominently in the future. 

## Potential lab and quiz questions

- Create and interpret SCC models
- Create DAGS
- Identify R code that makes a particular DAG
- D-Separated or not

# Tasks

- [ ] Update the lab
- [ ] Add lab code to Posit (if we still use Posit Cloud)
- [ ] Create a module quiz
- [ ] Add module quiz code to posit (if we still use Posit Cloud)
