### ISSUE TITLE
Overall revisions for Fall 2024

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#56]
# Overview

These revisions aren't specific to any individual module.

# Tasks

- [ ] Don’t use Posit Cloud.
- [ ] Convert all lab warm-ups to PP and Poll everywhere.
- [ ] Lab warm-ups will be in Canvas only, not Word.
- [ ] Labs will be in Canvas and qmd files, not Word.
- [ ] Quizzes will be in Canvas and qmd files, not Word.
- [ ] Labs and quizzes can/should ask questions that require students to recall information from previous modules. Libby was good about this.
