### ISSUE TITLE
Confounding Module Revisions - Fall 2024

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#57]
# Overview

A running list of little tasks to prep for Fall 2024.

## Lab warm-up

- I cleaned it up a little bit in Fall 2023, but there are still lots of comments in the PP slides and lots of room for improvement. 
- There are some slides at the very end that cover deconfounding methods. We need to simulate some data to show how they work. 

## Lab

- In Fall 2023, I used the lab wholesale without making any edits. It looks like many, if not all, of the DAG questions are from Hernan's videos. That isn't necessarily a problem. However, I should probably also add some of my own questions.
- Create questions to walk them through scenarios where the traditional criteria will and will not lead us to the same result as using a DAG and structural criteria. See slides 20-22 in the lab warm-up. Include simulated data. Started this in confounding_development.qmd.
- Create questions to walk them through scenarios where the change in estimate criteria will and will not lead us to the same result as using a DAG and structural criteria. See slides 17-19 in the lab warm-up. Include simulated data. Started this in confounding_development.qmd.
- I may want to walk them through using ggdag to answer questions about the DAGs.
- I may want to add some questions about deconfounding (e.g., regression).
- I may want to work through some kind of scenario with data (including a refresher on previously covered material).

## Module quiz

- I made it very quickly on the morning of the lab. It will likely need a lot of cleaning up and improving. 
- See the notes above about the lab and translate them to the module quiz.

# Tasks

- [ ] Review the comments in the lab warm-up slides.
- [ ] Move the lab warm-up questions from Socrative to poll everywhere.
- [ ] There are some slides at the very end that cover deconfounding methods. We need to simulate some data to show how they work. 
- [ ] Make the confounding lab DAGs in R with diggity. They are currently made in PowerPoint or something.
- [ ] Walk through examples demonstrating _why_ the change in estimate and traditional criteria don't always work.
