### ISSUE TITLE
Cohort Studies COL Revisions - Fall 2024

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#60]
# Overview

- In Fall 2023, I pieced this COL together from some older COL quizzes.
- Review the questions.
- Do any existing questions need to be improved?
- Are all the major topics hit on?
- I didn't add any questions from The Book of Why yet.

# Tasks

- [ ] Review the current version of the COL
- [ ] Add questions from The Book of Why chapter 7
- [ ] Add questions from the R4Epi Cohort chapter (once written)
