### ISSUE TITLE
Case-control Studies Module Revisions - Fall 2024

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#64]
# Overview

A running list of little tasks to prep for Fall 2024.

## Lab warm-up

- In Fall 2023, I combined the case-control study design and analysis labs into a single lab warm-up.
- The questions are too difficult. They need to be reading comprehension only.
- Possibly add more information about primary vs secondary study base (see comments below).
- Calculate the OR from a 2x2 table first, then from logistic regression.

## Lab

- In Fall 2023, I combined the case-control study design and analysis labs into a single lab.
- It feels like a grabbag of questions rather than the questions building on each other. I guess that isn't necessarily a problem for now, but I'd like to give it more of a flow in the future.
- I'm noticing that a lot of the questions about case-control study design are from the "Remember" section of Bloom's Taxonomy. Can you make them more applied?
- Add a lot more calculating and interpreting measures of random error (p-values, CI's, Chi-Square, etc.)
- There were several questions in `Lab: Case-control Study Analysis` that I didn't move over to the new `Lab: Case-control Studies`. They weren't necessarily "bad," they were just repetitive. They were all about matched ORs. I'm deleting `Lab: Case-control Studies` in Canvas, so you will have to go back to 2022 to look them up if you want them in the future.
- Make sure to cover the study base principle.

## Module quiz

- In Fall 2023, I combined the case-control study design and analysis module quizzes into a single module quiz.
- I made it very short and simple. It needs to be improved in the future, but not randomly. It should reflect that material in the lab.

# Tasks

- [ ] Update the Q7 ("Homogeneity of effects") on the COL quiz. In Fall 2023, the correct answer was listed as a "blank" answer box. I tried to change the correct answer to "There is evidence for the presence of multiplicative effect modification." However, I got an error saying that I couldn't because people had already taken the exam. Make sure to change this before anyone takes the exam this semester.
- [ ] Improve slides. I have a good first draft. I think the priority should be on adding regression to the analysis slides.
- [ ] Edit the lab questions as needed (see what feedback Ann and Devesh have)
  - [ ] Improve or rewrite the question of frequency matching
  - [ ] Improve the feedback on the identify a nested case-control study question.
  - [ ] Add feedback for Feedback: Frequency matching applied
- [ ] Edit the quiz questions as needed
- [ ] Add R4Epi reading to module overview page.

**Comment by mbcann01** [comment]
# Primary vs secondary base
Primary base defined by the population under study
- Population-based studies
- Difficult to get every case

Secondary base defined by case definition
- Study base are those who would have been selected as cases if they developed the disease
- Hospital-based studies
