### ISSUE TITLE
Adjust the course calendar for Fall 2023

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/epi_3_public#8]
# Overview

In Fall 2022, I originally scheduled the cross-sectional module to open on 12/5/22, the lab to take place on 12/13/22, and the quiz to be due on 12/18/22. However, that is finals week and I’m not allowed to have class. So, I had to cancel that module. In the future, I will need to do something to get around this problem.

In Fall 2023, without any changes,  the cross-sectional module will open on 12/4/23, the lab will take place on 12/12/23, and the quiz to be due on 12/17/23. However, the last day of class is 12/5/23. So, we have to make an adjustment.

Right now, I'm thinking about maybe combining `Getting Started with R and RStudio` with `Data Transfer`. Although, that is a lot of R in one week for a class that isn't about R and students who likely won't know any R on the way in. 

Another option is to drop  `Data Transfer` altogether and just create our own data frames at the beginning of every lab/quiz. I actually kind of like this idea right now. I just need to see how that will affect the other course materials. 

An additional option is to combine `Cohort Study Design` and `Cohort Study Analysis` into one module: `Cohort Studies`. And do the same with case-control studies. This is how Epidemiology By Design and Modern Epidemiology are both structured.

## Potential new module list

2023-07-20: Here is a draft new module list based on the information above and some of the other issues in this project board.

1. **Getting Started with R and RStudio**. Teach them how to get it on their computers, open it, and create some data frames. The goal will not be to teach them R programming. It will simply be to be able to use R as a tool for learning epi methods in this class.
2. **Measures of Occurrence**. Add non-regression survival analysis (see #20). Introduce probability (see #16).
3. **Random Error**. This would be new (see #19). 
4. **Measures of Association**. Add non-regression survival analysis (see #20). Introduce conditional probability (see #16).
5. **Introduction to Regression**. 
6. **Causal Inference**.
7. **Bias**.
8. **Confounding**.
9. **Effect Measure Modification**.
10. **Experimental Studies**. This would be new.
11. **Cohort Studies**.
12. **Case-Control Studies**.
13. **Cross-sectional Studies**.

# Tasks

If I'm going to make this change, I need to update the following documents, websites, etc.

- [x] The [course calendar](https://uthtmc.sharepoint.com/:x:/s/SPHCannellEpiIII/EZ93WNLrF7NJgo86YCPpys4B4dlX-MJ0bJUSnEI-hlKNxw?e=VbOwUa) (Use the July 20, 11:13 AM version as the backup)
- [x] Categories on the [GitHub project](https://github.com/orgs/brad-cannell/projects/11/views/2)
- [x] Module list on in the SharePoint (created a backup of old module structure in Old > Fall 2022 Structure)
- [x] Canvas modules - including unlock dates
- [x] Module list on in the [epi_3_public repo](https://github.com/brad-cannell/epi_3_public)
- [x] Module list on in the [epi_3_private repo](https://github.com/brad-cannell/epi_3_private)
- [x] Reading list
